### ISSUE TITLE
Nickname invalid

### ISSUE THREAD

**Issue by jonashelsen** [AskalotCQA/askalot#3] opened 2016-08-30 08:34 UTC
I tried logging into askalot but it bumps me with the following error message:

validation failed: nickname invalid

for the record my nickname is Jonas-H, could it be that the askalot nickname parser does not allow for "-"?

Thanks!

**Comment by isrba** [comment] 2016-08-31 19:22
Thank you very much for this bug report.

The problem was caused by different characters allowed in username in Askalot and in edX. edX allows  "letters, numbers, underscores (_), and hyphens (-)." Askalot originally allowed the same characters except hyphens. We have just add a hyphen to validation regexp and deployed the new version at edX.

**Comment by adrianhuna** [comment] 2016-10-01 17:36
Closing this issue as the changes have been implemented.

**Closed by adrianhuna** 2016-10-01 17:36 UTC
